### ISSUE TITLE
Overwriting Ember.Handlebars.helpers.action causes unpredictable testing behavior

### ISSUE THREAD

**Issue by kbullaughey** [runspired/ember-mobiletouch#10]
In the `ember-mobiletouch` initializer the `{{action}}` helper function gets overwritten. However this only happens in `qunit` acceptance tests and not component tests. Additionally, this is not cleaned up on `Application#reset()` which causes unit tests executed before the first acceptance test to behave differently than unit tests executed after the first acceptance test. 

This seems undesirable. Although I'm not sure what the best approach should be. Here are some ideas:

0. Don't put this in an initializer and instead have it executed once, as one usually does when extending `View` or reopening classes. 
0. Provide a cleanup routine that one can call inside of acceptance test `teardown` methods that undoes the modifications made in the initializer.

I have resorted to putting the following in my `setup` hook for acceptance tests:

    oldAction = Ember.Handlebars.helpers.action;

And the reverse in my `teardown` hook:

    Ember.Handlebars.helpers.action = oldAction

Perhaps I'm doing my testing wrong. Thoughts?

**Comment by runspired** [comment]
The code is in the initializer to make certain it is executed automatically (otherwise you have to import the file).  It may be sufficient to follow the accepted answer here for not re-running the initializer: http://stackoverflow.com/questions/27154886/ember-cli-where-to-reopen-framework-classes

I'm open to a PR with that solution if it works, otherwise this will probably need to wait to the weekend.

**Comment by kbullaughey** [comment]
The problem is not rerunning the initializer. The problem is that the set up is not done in unit tests, when initializers are not run. Please see the comment on my pull request. I have opted for [this solution](http://stackoverflow.com/a/27245106/1366749) in the same stackoverflow question you cite.

I'm open to suggestions if this solution is not what you're looking for.

**Comment by runspired** [comment]
This should be resolved in 1.4.0

See https://github.com/runspired/ember-mobiletouch#testing

Let me know if you need or discover anything else, and thanks so much for the report!
