### ISSUE TITLE
support for doubletap

### ISSUE THREAD

**Issue by kbullaughey** [runspired/ember-mobiletouch#12]
I was trying to get `hammer.js` doubletap to work, and found that it would require some additional reorganization. 

I [hacked together a change][1] that allows the user to add a `doubleTap` handler to components and views, following your conventions. See [the long comment on my branch][2] for an explanation.

[1]: https://github.com/kbullaughey/ember-mobiletouch/compare/master...kbullaughey:doubletap
[2]: https://github.com/kbullaughey/ember-mobiletouch/blob/doubletap/addon/mixins/hammer-events.js#L144-L155

I'm curious if you're interested in trying to get this integrated more cleanly? I think it will take a change to your public interface, and so I'm curious what your thoughts are.

**Comment by runspired** [comment]
I hide new features behind config options.  e.g. default of `ENV.mobileTouch.useDoubleTap = false`

In a related note, I've been brainstorming the best way to add custom recognizers.  I have a mixin I'm about to add to the repo for supporting vertical pan and vertical swipe without breaking scroll everywhere else.  For more universal recognizers though, I'd love to expose an easy ability to configure them without loading even more into the config than I've already done (which already feels too heavy if you need to customize events).

I've been thinking of adding an optional file `app/recognizers.js` similar to liquid-fire's `app/transitions.js` in which these would go (and perhaps receive some convenience wrappers).

**Comment by kbullaughey** [comment]
Are you suggesting that I add a `useDoubleTap` flag and just wrap my code in a conditional statement checking this flag? Would you be happy with that as a solution for now, even though the fix I've suggested is kind of hacky?

**Comment by kbullaughey** [comment]
As a side note, I didn't find any tests for this addon. Do they exist somewhere or do you have a plan for testing? I'm happy to add tests for my modifications, but I wanted to follow your conventions.

**Comment by runspired** [comment]
> Are you suggesting that I add a useDoubleTap flag and just wrap my code in a conditional statement checking this flag? Would you be happy with that as a solution for now, even though the fix I've suggested is kind of hacky?

I'm merely saying new recognizers / behavior should be added behind a config flag.  The implementation can be reworked, I've got some serious work on the internals coming this weekend.

> As a side note, I didn't find any tests for this addon. Do they exist somewhere or do you have a plan for testing? I'm happy to add tests for my modifications, but I wanted to follow your conventions.

No tests yet, no formalized plan, but any help you could give here would be massively appreciated.

**Comment by runspired** [comment]
@kbullaughey If you want, you can PR your changes into the develop branch in advance of the weekend's internal cleanup/refactor.

**Comment by runspired** [comment]
See https://github.com/runspired/ember-mobiletouch#custom-recognizers
