### ISSUE TITLE
Taps don't trigger action handlers unless `on="tap"` is explicitly set.

### ISSUE THREAD

**Issue by linearza** [runspired/ember-mobiletouch#13]
Hi there

It seems the tap gestures don't work well implicitly. At first I thought it had to do with component nesting and actions not being passed through, but testing showed that though the tap gesture bubbles fine, for some reason actions aren't getting triggered. 

Please have a look at the demo I setup:
https://github.com/linearza/tap-debug

We've traced the origin of the issue so far back to, between line 16 and 46:
`app/initializers/ember-mobiletouch.js`

Some of the dependencies versions we use that might be affecting this include:

In package.json:
"ember-cli-htmlbars": "^0.6.0",
"ember-mobiletouch": "1.3.2",

In bower.json:
"hammerjs": "~2.0.4",
"handlebars": "~2.0.0",

**Comment by runspired** [comment]
I haven't had a chance to look into your demo too deeply, but with ember 1.9.1 this definitely should not be an issue.

A few things I did notice.

You are also using fastclick.js, this shouldn't interfere but it's not actually necessary.  fastclick and tap are roughly equivalent.

In that demo, you aren't using 1.3.2, you're using a custom fork of mobiletouch with a change that I can see would likely cause this issue:

The change: https://github.com/donovan-graham/ember-mobiletouch/commit/f89802160811df9d30ac4c588323b625c60cdd85

What it should be: https://github.com/runspired/ember-mobiletouch/blob/v1.3.2/app/initializers/ember-mobiletouch.js#L41-L44

**Comment by runspired** [comment]
I tried installing and running your demo tonight but bower barfed all over itself, I'll take another peek tomorrow.

**Comment by linearza** [comment]
Apologies for the delay. I quickly worked through your suggestions. At the time version 1.3.2 didnt propagate tap gestures at all, so thats why we resorted to the fork. I updated the forks initialiser with the code block but that didnt improve anything. However, after upgrading to version 1.4.2 things seem to be working perfectly! Ive updated my repo in case you want to play around with it.

Thanks

**Comment by runspired** [comment]
Thanks for the feedback, glad to know it's working in 1.4.2
