### ISSUE TITLE
app does full refresh when link-to helper clicked or tapped

### ISSUE THREAD

**Issue by koriroys** [runspired/ember-mobiletouch#14]
Did I miss something?

**Comment by runspired** [comment]
Could you post your link-to helper code as well as what versions you are using of ember-mobiletouch and of ember?  This is likely to be an issue with your link-to helper.

**Comment by koriroys** [comment]
Sure!

Just using the standard link-to (which if I read correctly from the docs overrides the built in one?):

```handlebars
{{#link-to 'projects.show' project}}
  {{project.title}}
{{/link-to}}
```

"ember-cli": "0.2.0-beta.1"
"ember": "1.10.0",
"ember-data": "1.0.0-beta.15",

**Comment by runspired** [comment]
Thanks, which version of mobiletouch?

Could you also post the html output of that link-to?  If you use chrome's dev tools and check the box for "preserve log", is there an error thrown just before the refresh?

The only linkview mod that affects this is changing the LinkView's eventName from 'click' to 'tap'.  It's the same as doing `{{#link-to 'projects.show project eventName='tap'}}{{project.title}}{{/link-to}}`

Link-to's by default use anchor (`<a>`) tags, the default behavior of which is to do a full page ref on click if it has an empty `href` (e.g. `<a href="">My Link</a>`.  mobiletouch prevents default behavior after clicks on all links with an href that don't have a custom protocol (e.g. 'mailto:' or 'tel:').  It would not bust the click on an anchor without href, e.g. `<a>My Anchor Tag</a>`

**Comment by koriroys** [comment]
Yep, sorry.

"ember-mobiletouch": "1.4.1",

Actually it seems that link-to works fine, but that putting any kind of div (with content) inside it causes a full refresh.

<h3>Doesn't work:</h3>

```handlebars
{{#link-to 'projects.show' project}}
  <div>
    {{project.title}}
  </div>
{{/link-to}}
```

html output:

```html
<a id="ember655" class="ember-view active" href="/projects/23">
  <div>
    Take over the world
  </div>
</a>
```

<h3>Works:</h3>

```handlebars
{{#link-to 'projects.show' project}}
  {{project.title}}
{{/link-to}}
```

html output:

```html
<a id="ember682" class="ember-view active" href="/projects/23">
  Take over the world
</a>
```

<h3>Also works but kinda useless:</h3>

```handlebars
{{#link-to 'projects.show' project}}
 <div></div>
 {{project.title}}
{{/link-to}}
```

html output:

```html
<a id="ember655" class="ember-view active" href="/projects/23">
  <div></div>
  Take over the world
</a>
```

**Comment by runspired** [comment]
Thanks!  I only bust the click based on the event target, not the current target, so it looks as though the issue is that I need to check the event's current target as well during bubbling.  Might have some time tonight to implement the fix.

**Comment by runspired** [comment]
@koriroys Version 1.4.3 should resolve this issue, but I'll leave this open until it's been tested in the wild for a bit.

**Comment by koriroys** [comment]
Thanks!. I'll try to integrate it with my project again and see how it goes!
