### ISSUE TITLE
clicking on {{#link-to ... }} links randomly causes page to refresh

### ISSUE THREAD

**Issue by kbullaughey** [runspired/ember-mobiletouch#16]
For some reason when I click on `{{#link-to "some-route"}} ... {{/link-to}} ` links that route to a new place in my application the page randomly refreshes and loads the whole app again at the URL of the route I'm trying to visit. So I get to the right destination but the whole app gets reloaded as if I typed the URL into the browser address bar. 

I can remove the problem by removing `ember-mobiletouch` and then cause it again by reinstalling `ember-mobiletouch`. 

I only noticed this problem after upgrading to 1.4.2 from 1.3.2. 

I haven't had time to dig in to the problem. I thought I would ask in case this problem has cropped up before.

**Comment by runspired** [comment]
Same as #14, has been tracked down.  I'm less aggressive about busting clicks on links than I used to be, seems it'll need to rethought.
