### ISSUE TITLE
Events in config not being overwritten

### ISSUE THREAD

**Issue by dgavey** [runspired/ember-mobiletouch#19]
I see you have added a new section for allowing certain default events through, which is great!  Unfortunately in my testing, the updates overrides I added to my environment.js don't seem to be taking.

I added this: 

ENV.mobileTouch = {

    //what default Ember events should be disabled
    events : [
      'mousedown',
      'mouseup',
      'click',
      'dblclick',
      'mousemove',
      'mouseenter',
      'mouseleave'
    ]

  };
So that the touchStart, touchEnd, touchMove and touchCancel would be allowed through. However that doesn't seem to be the case.  When I remove those events from your default config however it works just fine.  

So it seems that the config file doesn't seem to be overriding.  Or I'm doing something wrong in my config file.  Would appreciate any suggestions you have.  I'm using mobile-touch 1.4.2 and Ember 1.10

**Comment by runspired** [comment]
This definitely sounds like an issue with the config file not being merged with the defaults correctly, I'll take a peek and patch tonight as necessary.

Out of curiosity, what use cases lead you to re-introduce the touch events?

**Comment by dgavey** [comment]
Thanks, I'd appreciate that!  I

t's for the same reason I wrote about in a previous issue.  I have a sound scrubber that requires dragging the scrub bar across.  I have custom code that handles it right now using the touchStart etc.  I plan on eventually adding a custom touchDrag or something like that in the future. So I don't have to get access to the raw touch events.  If only Hammer had a drag api, it would be fantastic.  But that project seems to be on a serious break right now.

Somewhat of a separate question, but if I were to add some sort of drag API, could I do it here in this project as a PR, or would I have to add it to Hammer?

**Comment by runspired** [comment]
@dgavey I'm hoping to become a partial maintainer of Hammer along with many others, the current maintainer has been silent so far on allowing group ownership though.  Hopefully that happens soon!

If that does happen, I think drag will be added as an API given that in my experience using `pan` for dragging really doesn't cut it.

Regardless, I'd love a PR here for drag.  It would need to be behind a feature flag (e.g. `ENV.mobileTouch.drag=false` by default), and it would need tests (the 1.5 release will be fully tested).

**Comment by dgavey** [comment]
Ok sounds good, it's essential for not just our scrubber but other items we want to implement (like sliding menus, pull to refresh etc.) I'll have to hack that in this week, but I'll see if I can find time to implement it here as well in a less 'hacky' sort of way.

I hope the Hammer project gets going again, that would be great news.

**Comment by dgavey** [comment]
Updated to 1.4.5 and the events still were not reading from my config.  I will be submitting a PR with a fix for it shortly.
