### ISSUE TITLE
Pan events loses original target

### ISSUE THREAD

**Issue by donovan-graham** [runspired/ember-mobiletouch#2]
Hi

I have an app that currently implements ember-hammer/hammer.js@1.0  and would like to use your addon instead.  I switched out addon's and updated the references in my code to reflect the new hammer.js@2 panstart panleft and panright syntax.  All good so far.  

I have a couple of element which implement a touch drag event, like sliding in a hamburger menu from the right and sliding a list element to the right to reveal additional menus and action options.  What I've found it that the current implementation of binding Hammer to document.body and using event delegation to find the target, end's up loosing the element currently being dragged/panned if you finger movement goes outside the element's bounding box.  In such case the panstart event is fired, some of the panleft/panright events are recognised, but suddenly the target element is lost and the panend event isn't fired.  This is also happens when you have a horizontal element in a long list and your finger traces a kind of arc (left and down) movement.  The starting touch is on, say, list item 1 but the ending touch, is on list item 2 or 3.  

These are fine for tap and swipe events where you don't need continuous feedback, but drag events which rely on a consistent target get lost.  

A solution could be to collect the original target element on panstart and always delegate to it until a pandend is fired. Alternatively you could allow defining multiple hammer instances, and let the user define which level of event delegation their comfortable with.  In our case, this would be the list container, rather that the list items, but not the document body.

Here's a simple example from Hammer.js docs
https://github.com/hammerjs/hammer.js/blob/master/tests/manual/multiple.html

Any thoughts or suggestions?

Many thanks
D

**Comment by runspired** [comment]
I'd be happy to look into this, could you provide a jsbin reproducing this behavior?

**Comment by donovan-graham** [comment]
Here's an example ember app I've put together for you. 
https://github.com/donovan-graham/mobiletouch

**Comment by donovan-graham** [comment]
I also notice when panning, that a single panLeft event is being called before panStart and then the rest of the panLeft events.  This seems like unexpected behaviour.

**Comment by runspired** [comment]
@donovan-graham I see you opened an issue on Hammer.js as well, while I'd prefer this was fixed there, that project's maintainer is looking for a new maintainer and is unlikely to fix it soon.

I built mobile-touch in such a way that we can switch out the underlying gesture engine easily, it just requires that gesture engine or a binding to it to emit DOM events with the appropriate names.

Given that Hammer.js's maintainer is stepping down, if a new maintainer does not step forward (I'm considering it, but uncertain I have the time), I'd be open to using a new lib.

**Comment by donovan-graham** [comment]
Thanks for your reply. I've implemented a workaround for the touchstart
event, and currently am creating a new instances (on top of the default
document.body instance) of hammer to handle the end cases which need to
listen for pan events.

Regards, D

Kind Regards
Donovan Graham

donovan@platform7.com

UK +44 (0)208 1444283
SA +27 (0)82 7804636
SA +27 (0)21 5522338

**Comment by runspired** [comment]
@donovan-graham does your new approach of listening to `panMove` remove the need for the extra instances in your app?  I ask because in our own app I implemented something I call `touchZones`, essentially a set of CSS class that allow you to invisibly expand the borders of an element using `::before` to capture actions around the edges of critical buttons / gesture zones more consistently.
