### ISSUE TITLE
NPM Install fails

### ISSUE THREAD

**Issue by dgavey** [runspired/ember-mobiletouch#25]
I'm trying to install 1.4.3 and I got an NPM install error.

shasum check failed for /var/folders/yc/rkmd352n1498h0h6sgr1r4lr0000gn/T/npm-18850-ccda4ea4/registry.npmjs.org/ember-mobiletouch/-/ember-mobiletouch-1.4.3.tgz
npm ERR! Expected: 72414831fb031f18e85eb2f29b4248e617ebe0d9
npm ERR! Actual:   85f291fa8e87085aca112738af21bb9b388efc6f

My node and NPM are up to date.

**Comment by runspired** [comment]
Have confirmed this and confirmed that it does not appear to be an issue with npm being down (which apparently has led to this in the past).  Trying to trace down potential causes, will republish as soon as possible.

**Comment by runspired** [comment]
Re-release 1.4.3 as 1.4.4 to see if it was just an issue with that build.  Same issue.  Updating to the latest node and npm to see if it will make this go away.

**Comment by runspired** [comment]
I upgraded to node 0.12.0 and released 1.4.5 using it.  Was able to download and install via npm successfully.

**Comment by dgavey** [comment]
1.4.5 installed fine for me too, thanks again!
