### ISSUE TITLE
Actions with parameters not working

### ISSUE THREAD

**Issue by huafu** [runspired/ember-mobiletouch#3]
When using an action with some paramters, it triggers js errors (the arguments are not handled as they should I guess on the overridden `action` helper:
```handlebars
<button {{action 'someAction' myFirstParam mySecondParam}}>click here</button>
```

I guess it's related to another issue I have where the action of a form would not be called:
```handlebars
<form {{action 'someAction' on='submit'}}>
  <!-- ... -->
  <button type="submit">Send</button>
</form>
```

The `someAction` never get called here.

**Comment by runspired** [comment]
the 'submit' button error is likely the click cancel set to prevent default behaviors of clicks, I'd start by looking there.
