### ISSUE TITLE
Keyboard open triggering focus on input

### ISSUE THREAD

**Issue by dgavey** [runspired/ember-mobiletouch#33]
I have to inputs vertically aligned above each other. It's a login form.  If the user taps on the username the keyboard opens and then after about 500ms the password field will gain focus.

I was able to determine that if I disabled either focus event between line 152-159 in the event-dispatcher.js then the second input does not gain focus.

I was hoping that this would fix my ongoing transition click issues, but it doesn't seem to be the same issue.

**Comment by runspired** [comment]
What environment specifics?  I have similar forms in all my apps and have not observed this behavior (cordova ios, chrome, safari, NW.js)

**Comment by dgavey** [comment]
Cordova iOS. 
This occurs in both the emulator for iOS and an actual device. Though it's a bit trickier to make happen on the emulator, you have to click quickly to get it to happen.

**Comment by runspired** [comment]
>  If the user taps on the username the keyboard opens and then after about 500ms the password field will gain focus.

Dumb question, do you mean the "username label"? Is the label misnamed?

**Comment by dgavey** [comment]
Sorry, not very clear.  In this case I have two inputs:

[USERNAME]
[PASSWORD]

They are vertically aligned like above.  If the user clicks on the 'username' input when the keyboard opens the view pans so that the 'password' input is positioned exactly on the screen where the user tapped on the username input and 500ms later the password field gains focus.

Hopefully that is a bit more clear.

**Comment by runspired** [comment]
Ah, so this is the same ghost click as before then.  I'm going to close this and reference it in the other, and update the name to reflect that this seems to be ghost clicks after clicks on inputs.

**Comment by dgavey** [comment]
Ok, but I'm not sure if it's the same.  As I mentioned above, when I tested the route transitions after commenting out the focus events, it did not fix the route transition issue but did fix the password focus issue.  Though I have to say the issues do seem to be very similar.

**Comment by runspired** [comment]
Similar enough I'd be very surprised if they didn't have the same underlying cause.

**Comment by dgavey** [comment]
Is there something I can do to help you track this down? I keep playing in the code trying to figure out where it's breaking but not having much luck.

**Comment by dgavey** [comment]
Another thing I just noted.  You have to tap very fast to make this problem happen. A slower tap on the initial input does not make the second input gain focus.

**Comment by runspired** [comment]
Related issues and subject matter:

This http://stackoverflow.com/questions/4862599/click-delay-on-iphone-and-suppressing-input-focus
This http://ariatemplates.com/blog/2014/05/ghost-clicks-in-mobile-browsers/

**Comment by runspired** [comment]
It seems that a touchEnd busting strategy for some input elements is the way to go.  I'll take a peak into the internals of fastclick.js to see what else they came up with.
