### ISSUE TITLE
Bringing in ember-mobiletouch as a dependency results in a tmp folder with 700+MB

### ISSUE THREAD

**Issue by simonjefford** [runspired/ember-mobiletouch#35]
I have `ember-mobiletouch: "1.4.9"` in my package.json in an ember-cli 0.2.2 app. When I run npm install then `node_modules/ember-mobiletouch/tmp` contains 725M of files (according to `du -h`)

**Comment by runspired** [comment]
Ember-mobiletouch does not include a `/tmp` directory, nor does it build one.  This is an issue to address with either `ember-cli`, `broccoli` or `npm`.  There's a discussion here of common reasons large tmp folders occur with broccoli: https://github.com/broccolijs/broccoli/issues/187

**Comment by simonjefford** [comment]
That doesn't appear to be strictly true. ember-mobiletouch-1.4.9.tgz as downloaded from the npm registry is 111MB big and contains a rather large tmp folder.

https://gist.github.com/simonjefford/bcc97fd0c586d638d810

**Comment by runspired** [comment]
Looks like ember-cli doesn't include `/tmp` in the list of directories excluded in `.npmignore`, when packaging an addon, but since it is present the `.gitignore` rules are ignored.  I release `1.4.10` at a much smaller, happier size.  Thanks!

**Comment by simonjefford** [comment]
That was fast work - thanks for fixing!
