### ISSUE TITLE
Fastclick is missing after install

### ISSUE THREAD

**Issue by ryanbillingsley** [runspired/ember-mobiletouch#51]
I needed to run the `ember-cli-fastclick` generator in order to have the bower component installed.

**Comment by runspired** [comment]
With 2.0 fastclick is completely removed.

**Comment by ryanbillingsley** [comment]
I installed 2.0.0-beta1 and got an error that fastclick was missing.

**Comment by runspired** [comment]
There's a little hook left over in the blueprint that needs removed, I'll make sure to clean that up for the next beta.
