### ISSUE TITLE
Glimmer compatibility

### ISSUE THREAD

**Issue by runspired** [runspired/ember-mobiletouch#52]
`Ember 1.13.0-beta.x` removes the ability to use `Ember.Handlebars.helpers.view.helperFunction` to create helper functions.  This severely impacts our ability to make the `action` helper more useful.  It's been suggested that we could programmatically re-write `{{action}}` helpers to include `on="tap"` if no event were specified, but I'm not sure that would really be the best way forward.

There are a lot of changes coming to the action helper, most of which will remove this repo's need to modify the helper at all.  Until that time I would like to find a way to maintain changing the default action event from `click` to `tap`.

**Comment by varoot** [comment]
Does this mean that it's safer to add `on="tap"` to every action for now?

**Comment by runspired** [comment]
@varoot yes, it does.

**Comment by timohofmeijer** [comment]
Does this mean this library won‘t work with `Ember 1.13+` (Glimmer) for now? 
I‘m getting `Uncaught TypeError: Cannot set property 'helperFunction' of undefined`

**Comment by runspired** [comment]
@timohofmeijer Correct.  I'm trying hard to rectify this but unfortunately the new actions RFC that was implemented is deficient.  It dramatically improves performance and ease of use of actions (in our favor) when used on components, but leaves actions on elements far behind without an easy path to improve them.

I've talked with core team members, and they would be alright with a small RFC to improve the state of actions on elements.  Unfortunately, my time is currently pulled too many ways.  Improving Ember to enable better action behavior on elements is preferred to finding another way to hack improved element actions into ember.

Regardless of path taken, we'll be removing the ability to have multiple triggering events, although in it's place we'll be capable of multiple action handlers per component/element so the same ability will be preserved but implemented differently.

It's been suggested by @rwjblue (repeatedly) that we use an AST tree walker to rewrite action handlers that have no `on=""` specified to use `tap` by default. This sounds to me like the ideal interim approach until closure actions work with elements. I'm not very familiar with the concept but suspect @abuiles would be able to point be in the right direction based on his work in `ember-watson`.

**Comment by runspired** [comment]
Something I'm mulling right now is that maybe I need to re-evaluate `tap` vs `click` for `ember-mobiletouch` going forward.

As much as I like `tap` as an API and for it’s semantics, it’s just not going to work easily with ember 1.13 and beyond.  While the two events mean and behave differently, their needs are unfortunately greatly intwined.

The proffered solution is to build an AST walker and rewrite `on-click` to `on-tap`, but if we do this, anything that actually needed a click breaks.

On the other hand, if we don’t build a walker, and just require devs to specify `on-tap` themselves at all times, then any addons with components that define their own handlers break.

I’m instead mulling the idea of modifying `tap` to be able to `preventDefault` the source event in a normal manner.

It would largely be a shell function, but would delegate to `touchStart` or `mouseDown` whichever pointer event was used to start the tap process, and would log that it occurred (along with the event’s coordinates).

`click` on mobile doesn’t trigger `mouseDown` or `touchStart`, so the native simulated clicks wouldn’t be capable of being preventDefault-ed via the `tap`.

If we did nothing, `click` handlers would often end up with TWO clicks and always need debounced.

One thing we are guaranteed of is that in the case that both fire, the `tap` will fire before the native click.  We can inspect and tell whether an event is a true click or a tap.

If the `tap` is preventDefaulted or the handler returns false, when we get the `native` click we check it’s coordinates and cancel it, never allowing it to trigger the action or link in the first place.

Thoughts?
