### ISSUE TITLE
Install error - "ember generate"

### ISSUE THREAD

**Issue by bkCDL** [runspired/ember-mobiletouch#53]
I was excited when I discovered ember-mobiletouch. I looks to have great potential for my app. I'm trying to install it for the first time today on my Ember-CLI app. I'm using Node 0.10.36, Ember-CLI 0.2.3, and Ember.js 1.11.1. When I type `ember install ember-mobiletouch`, I get this error

> *The `ember generate` command requires an entity name to be specified. For more details, use `ember help`.*

Any tips on how to resolve this?

Bryan

**Comment by mapohjola** [comment]
I am having the same problem with Ember.js 1.11.1 and Ember-CLI 0.2.3. When I am trying to use the helpers I only get "Uncaught Error: Assertion Failed: A helper named `action-area` could not be found".

**Comment by bkCDL** [comment]
I upgraded to node 12.4 and ember-cli 0.2.7. Now I'm getting a different error when I run:

    $ ember install ember-mobiletouch

Here's the console output:
>version: 0.2.7
>Installing packages for tooling via npm../media/bryan/DATA/ReportingWebsite/node_modules/ember-cli/node_modules/npm/lib/utils/locker.js:66
>    throw new Error(
>              
>    Error: Attempt to unlock /media/bryan/DATA/ReportingWebsite/node_modules/ember-mobiletouch, which hasn't been locked
>      at unlock (/media/bryan/DATA/ReportingWebsite/node_modules/ember-cli/node_modules/npm/lib/utils/locker.js:66:11)
>      at cb (/media/bryan/DATA/ReportingWebsite/node_modules/ember-cli/node_modules/npm/lib/install.js:1017:5)
>      at /media/bryan/DATA/ReportingWebsite/node_modules/ember-cli/node_modules/npm/lib/install.js:1021:20
>  at /media/bryan/DATA/ReportingWebsite/node_modules/ember-cli/node_modules/npm/lib/utils/locker.js:40:9
>  at cb (/media/bryan/DATA/ReportingWebsite/node_modules/ember-cli/node_modules/npm/node_modules/lockfile/lockfile.js:149:38)
>  at /media/bryan/DATA/ReportingWebsite/node_modules/ember-cli/node_modules/npm/node_modules/lockfile/lockfile.js:177:38
>  at FSReqWrap.oncomplete (fs.js:95:15)

(incidently, `sudo npm install ember-mobiletouch` runs just fine)

Bryan
