### ISSUE TITLE
form submit not working

### ISSUE THREAD

**Issue by abarax** [runspired/ember-mobiletouch#54]
Hi All,

I am having an issue with my custom button component when trying to submit forms.  The code looks like this:

    <form role="form" {{action 'login' on='submit'}} >
        {{loading-btn buttonLabel="Go"}}
    </form>

And my component:

    export default Ember.Component.extend({
        tagName: 'button',
        classNames: ['btn allow-click'],
        type: 'submit',
        click: function (){
            this.sendAction();
        }
    });

The click handler is definitely being called but sendAction appears to do nothing. I suppose this is due to preventDefault being called by mobiletouch at some point.

Is this a bug? Or is there a piece of documentation I missed that details what to do here?

I actually end up having to do this which doesn't seem right:

    var $target = Ember.$(e.target);
    $target.closest('form').trigger('submit');

**Comment by kbullaughey** [comment]
Try altering your component as follows:

    export default Ember.Component.extend({
      tagName: 'button',
      classNames: ['btn'],
      type: 'submit',
      attributeBindings: ['type'],
    });

Type is not automatically added as a tag in the html. And it appears you don't need an event handler.

**Comment by abarax** [comment]
Thanks for the response. I have tried this and it does not work.

**Comment by kbullaughey** [comment]
Please try again with the the version on master. I fixed some things that should have solved this problem.

**Comment by abarax** [comment]
Confirmed working. Thank you sir.
