### ISSUE TITLE
TextArea's not focusing

### ISSUE THREAD

**Issue by abarax** [runspired/ember-mobiletouch#57]
There is bug with using ember's built in text area helper:
    {{textarea}}

It is probably related to these lines https://github.com/runspired/ember-mobiletouch/blob/master/addon/overrides/event-dispatcher.js#L166

Ember uses the `<textarea/>` tag which is not accommodated by this code.

I would submit a patch but am a little too unfamiliar with the code at this point.

Thanks.

**Comment by kbullaughey** [comment]
What behavior are you observing and what behavior are you expecting to see? related to focusing?

**Comment by abarax** [comment]
Ah, sorry. Maybe it is not a bug, I am not sure. 

It just requires a long tap in order to be selected.

It may only be noticeable when using a mouse and emulating on iOS or on chrome and setting device to iPhone

**Comment by runspired** [comment]
There's a fix for this on he develop branch that needs ported

**Comment by runspired** [comment]
https://github.com/runspired/ember-mobiletouch/commit/44ce25f3af25ce8838eaef8d667019f474372a02

**Comment by abarax** [comment]
Ah thanks for that.
