### ISSUE TITLE
input of type file

### ISSUE THREAD

**Issue by abarax** [runspired/ember-mobiletouch#58]
I have a form element that looks like this:

    <input type="file" name="file" accept="image/*;capture=camera">
Clicking on this does not work.

If I change this line https://github.com/runspired/ember-mobiletouch/blob/master/addon/overrides/event-dispatcher.js#L166 to include 'file' it works in mobile browser but still does not work in a regular browser.

Let me know if you need more info.

**Comment by runspired** [comment]
Thanks for the report, this issue will be fixed by the tap conversion, and currently should be mitigated via use of needsclick.

**Comment by abarax** [comment]
Unfortunately `needsclick` does not seem to fix it. 

I have tried applying the class to the input element and to the component itself.

Thanks for the response, I may just have to wait for the tap conversion.

**Comment by ssendev** [comment]
```hbs
<label>
  {{input type='checkbox' checked=foo class="needsclick"}}
  foo
</label>
```
can't be clicked either. a click on foo will do nothing while a click directly on the checkbox will toggle the value but not update the checkmark. subsequent clicks won't even change the value anymore.

tested on master and 2.0

**Comment by runspired** [comment]
@ssendev labels are definitely a different issue altogether, and as I mentioned before they will be solved by reworking the `click` event to function properly whether it was actually a `click` or secretly a `tap` (see #56 )

> subsequent clicks won't even change the value anymore.

If this works once, but only once, it's more likely your code.
