### ISSUE TITLE
Action helper does not support HTMLbars.

### ISSUE THREAD

**Issue by jarredkenny** [runspired/ember-mobiletouch#6]
Hello,

It appears that when ember-mobiletouch overrides Embers action helper it breaks compatibility with HTMLbars. 

I am receiving the following error when using the action helper with ember-mobiletouch installed.

Uncaught TypeError: Cannot read property 'call' of undefined

**Comment by runspired** [comment]
Thanks! I will be issuing a patch early this week as I migrate to HTMLbars myself.  Unfortunately, until the Ember team decides to make mobile environments a higher priority we're left overriding the default action helper, which is a private API and therefore subject to change.

**Comment by rwjblue** [comment]
I'm not sure where that comment comes from. We have always considered mobile support to be very important. I personally am happy to talk through what changes might be needed here....

**Comment by runspired** [comment]
I've got an open issue on ember related to this (for which I'd be happy to PR).

**Comment by runspired** [comment]
@jarredkenny check the develop branch if you can and let me know if you run into any issues.  So far it's looking good in my app but it'd be nice to have a second set of eyes.

**Comment by zjrosen1** [comment]
@runspired develop branch is working on ember-cli 0.2.0-beta.1 for me.
