### ISSUE TITLE
ember-cli-fastclick is not installed on ember install

### ISSUE THREAD

**Issue by ssendev** [runspired/ember-mobiletouch#61]
```
ember init
ember install ember-mobiletouch
```
results in 
````
Path or pattern "bower_components/fastclick/lib/fastclick.js" did not match any files
```
running 

```
ember install ember-cli-fastclick
```
solves it

--edit
okay apparently i am blind and the issue was already here #51

**Comment by lodalo** [comment]
I did not get the issue you are mentioning here. Here is my output:

> ember install ember-mobiletouch
version: 1.13.1
Installed packages for tooling via npm.
installing ember-mobiletouch
Installing browser packages via Bower...
  install package ember-cli-fastclick
Installing packages for tooling via npm...
  not-cached git://github.com/EightMedia/hammer.js.git#*
Installed packages for tooling via npm.
Installed addon package.

Mac OSX, node 12.4
