### ISSUE TITLE
pan events from outside the browser window are lost

### ISSUE THREAD

**Issue by ssendev** [runspired/ember-mobiletouch#63]
this is similar to #2. to solve it i wanted to capture the events at the top and redirect them so i added a application view and put the pan, panEnd listener there, but it still only listens to pans on the body (which means only the small area with welcome to ember since the body dosn't have height 100%). if the verticalPan mixin is added to the view panEnd is captured even if the mouse leaves the browser window. so is there another place to capture events from outside the browser window or is there a reason this dosn't work.
```
ember init
ember install ember-mobiletouch
```
```js
// app/views/application.js
import Ember from 'ember';
import VerticalPanMixin from "ember-mobiletouch/mixins/vertical-pan";
 
// export default Ember.View.extend({
export default Ember.View.extend(VerticalPanMixin,{
  panConfiguration: {direction: Hammer.DIRECTION_HORIZONTAL},
  panEnd(e) {
    console.log('view');
    console.log(e);
  }
});
```

**Comment by runspired** [comment]
This is expected behavior, you should fix the height of your body element.   Even if I move the listener to be directly on the Ember route element (which I actually think it is, but will double check) you would have this issue.

**Comment by ssendev** [comment]
no, the vertical-pan mixin solves the issue which demonstrates that it is possible. Increasing the body size would not help since events from outside the browser windows would still be lost. for an example of what i mean go to googlemaps unmaximize the browser and move the map, even when the mouse leaves the browser and is over the desktop or another window the map still moves.
