### ISSUE TITLE
GH-Pages: Primitives(Dropping) and Docs(Customizing) don't work

### ISSUE THREAD

**Issue by herom** [runspired/ember-mobiletouch#66]
Hey,
I've just came along this awesome plugin and I wanted to check out how one would build a **drag and drop** example, so I surfed to your examples page but I can't see the **Primitives --> Dropping** page, nor the **Docs --> Customizing** page (tested on Win 8.1/Chrome latest, iPad iOS Safari 8.3).

**Comment by runspired** [comment]
@herom The docs need updating, drag and drop got pushed to a branch and will be delayed until a separate addon project is ready

**Comment by herom** [comment]
Thanks @runspired - I was hoping to find a "working" solution for my ember application to incorporate drag & drop.... seems like I'm pretty much stuck at this topic as there are no other proper solutions out there I know of :disappointed:
