### ISSUE TITLE
Container lookup breaks component unit tests

### ISSUE THREAD

**Issue by Bargs** [runspired/ember-mobiletouch#69]
All of my unit tests that use the `moduleForComponent` helper are currently failing on the container lookup in mobiletouch's EventDispatcher override (line 46). I think this must have started with the 1.4.11 release when that line was added. In the context of the unit test, `this.container` is undefined. Maybe I'm missing something, but the existence of `this.container` on the EventDispatcher seems to be undocumented so I'm not sure it can be relied upon.

I'm going to try to update ember-qunit and see if that fixes it, but I thought I should drop a note here as well.

**Comment by Bargs** [comment]
Tried updating to the latest version of ember-qunit, no luck.

**Comment by ef4** [comment]
This will fix the issue once it ships in ember-qunit: https://github.com/switchfly/ember-test-helpers/pull/90

**Comment by runspired** [comment]
:+1:

**Comment by Bargs** [comment]
@ef4 Ah ha! Thank you. I see there's still some discussion on that PR, if you need someone to test anything out let me know.

**Comment by ef4** [comment]
@rwjblue has already released ember-qunit v0.4.7 with this fix.

(I'm pretty sure he's really an advanced Artificial Intelligence that needs no sleep or food. That guy we see at meetups is just his front man.)

**Comment by runspired** [comment]
confirm.  He is most definitely the product of some alien or artificial intelligence.

**Comment by runspired** [comment]
Closing as this is an upstream problem being addressed.
