### ISSUE TITLE
Having pan enabled prevents swipe action from firing

### ISSUE THREAD

**Issue by Bargs** [runspired/ember-mobiletouch#8]
Swipe doesn't work out of the box with the default config in release 1.3.2 but all the other events enabled by default do. I was using the action helper, and the bound action wasn't getting called at all on swipe.

After disabling the pan event in environment.js, swipes started working.

Let me know if I can provide any additional info that'll help.

**Comment by thatikuntap** [comment]
Hi, I am having same issue, how do you disable pan in environment.js.  

Thx

**Comment by runspired** [comment]
```
ENV.mobileTouch.use = ['tap', 'press', 'swipe'];
```

**Comment by thatikuntap** [comment]
I tried this, still swipe is not working, testing in chrome 40

**Comment by runspired** [comment]
I've never found Hammer's swipe recognizer to be very consistent, especially in a web browser.  Try fine tuning the recognizer's velocity and threshold settings.

```
ENV.mobileTouch.tune : {
      swipe : { velocity : 0.3, threshold : 25 },
    }
```

**Comment by thatikuntap** [comment]
still no response,  below is my environemnt settings


  ENV.mobileTouch = {
   
      //which gesture families to allow, will create a recognizer for each
      //a minimum of tap must be present, turning off unused gestures can help performance
      use : ['tap', 'press','swipe'],
   
      //whether to alias "press" to tap within Ember's eventing
      // very useful if you don't need to distinguish and don't want to lose
      // taps from people who tap longer
      alwaysTapOnPress : false,
      
      //whether links and actions should trigger tap behavior on press as well
      // if eventName or "on" has not been explicitly defined
      // currently does not work with actions
      defaultTapOnPress : true,
   
      //passed to new Hammer.Manager(element, options)
      options : {
         domEvents : true
      },
      
      //passed to the respective recognizer
      tune : {
        tap : { time : 250, threshold : 9 }, //Hammer default is 250 / 2
        press : { time : 251, threshold : 9 }, //Hammer default is 500 / 5
        swipe : { velocity : .3, threshold : 25 },
        pan : {},
        pinch : {},
        rotate : {}
      }
   
  };

**Comment by runspired** [comment]
This was a result of the Swipe recognizer needing to be set to recognizeWith the pan recognizer.  This has been fixed in 1.4.1

**Comment by thatikuntap** [comment]
I upgraded to 1.4.1, still swipe is not working

**Comment by runspired** [comment]
I'll reopen the issue if you can you reproduce it in a jsbin.  The default configuration in 1.4.1 definitely allows both swipe and pan gestures to work. That configuration is implemented here: http://codepen.io/anon/pen/bNLJbN?editors=001

**Comment by thatikuntap** [comment]
Swipe is working, Thanks a lot
