### ISSUE TITLE
should click ember test helper work out of the box for actions?

### ISSUE THREAD

**Issue by kbullaughey** [runspired/ember-mobiletouch#9]
I've started switching my app from `ember-hammer` to `ember-mobiletouch` and I was surprised to find that to get `{{action}}` based clicks to trigger in my tests, I need to use:

    triggerEvent('#some-selector', 'tap')

instead of:

    click('#some-selector')

Is this intended behavior? or perhaps I have configured something wrong. It feels like a bug to me, so I figured I'd ask here.

**Comment by runspired** [comment]
This is intended behavior.

See https://github.com/runspired/ember-mobiletouch#action-helper
